package io.aatricks.llmedge.image.diffusion.internal

import android.content.Context
import io.aatricks.llmedge.image.diffusion.LoraApplyMode
import io.aatricks.llmedge.image.diffusion.StableDiffusion
import io.aatricks.llmedge.image.diffusion.StableDiffusionLoadSupport
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

internal object StableDiffusionLoader {
    suspend fun load(
        context: Context,
        modelId: String? = null,
        filename: String? = null,
        modelPath: String? = null,
        vaePath: String? = null,
        t5xxlPath: String? = null,
        taesdPath: String? = null,
        nThreads: Int,
        offloadToCpu: Boolean,
        keepClipOnCpu: Boolean,
        keepVaeOnCpu: Boolean,
        flashAttn: Boolean,
        vaeDecodeOnly: Boolean,
        sequentialLoad: Boolean?,
        allowVulkan: Boolean,
        forceVulkan: Boolean,
        preferPerformanceMode: Boolean,
        token: String?,
        forceDownload: Boolean,
        flowShift: Float,
        loraModelDir: String?,
        loraApplyMode: LoraApplyMode,
    ): StableDiffusion =
        loadInternal(
            context = context,
            modelId = modelId,
            filename = filename,
            modelPath = modelPath,
            vaePath = vaePath,
            t5xxlPath = t5xxlPath,
            taesdPath = taesdPath,
            nThreads = nThreads,
            offloadToCpu = offloadToCpu,
            keepClipOnCpu = keepClipOnCpu,
            keepVaeOnCpu = keepVaeOnCpu,
            flashAttn = flashAttn,
            vaeDecodeOnly = vaeDecodeOnly,
            sequentialLoad = sequentialLoad,
            allowOpenCl = true,
            allowVulkan = allowVulkan,
            forceVulkan = forceVulkan,
            preferPerformanceMode = preferPerformanceMode,
            token = token,
            forceDownload = forceDownload,
            flowShift = flowShift,
            loraModelDir = loraModelDir,
            loraApplyMode = loraApplyMode,
            preferredBackend = null,
            allowBackendFallbackToCpu = true,
        )

    suspend fun loadWithRuntimeBackend(
        context: Context,
        modelId: String? = null,
        filename: String? = null,
        modelPath: String? = null,
        vaePath: String? = null,
        t5xxlPath: String? = null,
        taesdPath: String? = null,
        nThreads: Int,
        offloadToCpu: Boolean,
        keepClipOnCpu: Boolean,
        keepVaeOnCpu: Boolean,
        flashAttn: Boolean,
        vaeDecodeOnly: Boolean,
        sequentialLoad: Boolean?,
        preferPerformanceMode: Boolean,
        token: String?,
        forceDownload: Boolean,
        flowShift: Float,
        loraModelDir: String?,
        loraApplyMode: LoraApplyMode,
        preferredBackend: io.aatricks.llmedge.runtime.ComputeBackend,
    ): StableDiffusion =
        loadInternal(
            context = context,
            modelId = modelId,
            filename = filename,
            modelPath = modelPath,
            vaePath = vaePath,
            t5xxlPath = t5xxlPath,
            taesdPath = taesdPath,
            nThreads = nThreads,
            offloadToCpu = offloadToCpu,
            keepClipOnCpu = keepClipOnCpu,
            keepVaeOnCpu = keepVaeOnCpu,
            flashAttn = flashAttn,
            vaeDecodeOnly = vaeDecodeOnly,
            sequentialLoad = sequentialLoad,
            allowOpenCl = preferredBackend == io.aatricks.llmedge.runtime.ComputeBackend.OPENCL,
            allowVulkan = preferredBackend == io.aatricks.llmedge.runtime.ComputeBackend.VULKAN,
            forceVulkan = preferredBackend == io.aatricks.llmedge.runtime.ComputeBackend.VULKAN,
            preferPerformanceMode = preferPerformanceMode,
            token = token,
            forceDownload = forceDownload,
            flowShift = flowShift,
            loraModelDir = loraModelDir,
            loraApplyMode = loraApplyMode,
            preferredBackend = preferredBackend,
            allowBackendFallbackToCpu = false,
        )

    suspend fun loadFromHuggingFace(
        context: Context,
        modelId: String,
        filename: String? = null,
        taesdPath: String? = null,
        nThreads: Int,
        offloadToCpu: Boolean,
        keepClipOnCpu: Boolean,
        keepVaeOnCpu: Boolean,
        flashAttn: Boolean,
        vaeDecodeOnly: Boolean,
        sequentialLoad: Boolean?,
        allowVulkan: Boolean,
        forceVulkan: Boolean,
        preferPerformanceMode: Boolean,
        token: String?,
        forceDownload: Boolean,
        preferSystemDownloader: Boolean,
        flowShift: Float,
        loraModelDir: String?,
        loraApplyMode: LoraApplyMode,
        onProgress: ((name: String, downloaded: Long, total: Long?) -> Unit)?,
    ): StableDiffusion =
        withContext(Dispatchers.IO) {
            val resolved =
                StableDiffusionLoadSupport.resolveWanAssets(
                    context = context,
                    modelId = modelId,
                    filename = filename,
                    taesdPath = taesdPath,
                    token = token,
                    forceDownload = forceDownload,
                    preferSystemDownloader = preferSystemDownloader,
                    loraModelDir = loraModelDir,
                    onProgress = onProgress,
                    validateResolvedAssets = StableDiffusionLoadSupport::validateResolvedAssets,
                    inferVideoModelMetadata = StableDiffusionLoadSupport::inferVideoModelMetadata,
                )

            StableDiffusionLoadSupport.createLoadedInstance(
                context = context,
                resolved = resolved,
                taesdPath = taesdPath,
                nThreads = nThreads,
                offloadToCpu = offloadToCpu,
                keepClipOnCpu = keepClipOnCpu,
                keepVaeOnCpu = keepVaeOnCpu,
                flashAttn = flashAttn,
                vaeDecodeOnly = vaeDecodeOnly,
                sequentialLoad = sequentialLoad,
                allowOpenCl = true,
                allowVulkan = allowVulkan,
                forceVulkan = forceVulkan,
                preferPerformanceMode = preferPerformanceMode,
                flowShift = flowShift,
                loraModelDir = loraModelDir,
                loraApplyMode = loraApplyMode,
                preferredBackend = null,
                allowBackendFallbackToCpu = true,
            )
        }

    private suspend fun loadInternal(
        context: Context,
        modelId: String? = null,
        filename: String? = null,
        modelPath: String? = null,
        vaePath: String? = null,
        t5xxlPath: String? = null,
        taesdPath: String? = null,
        nThreads: Int,
        offloadToCpu: Boolean,
        keepClipOnCpu: Boolean,
        keepVaeOnCpu: Boolean,
        flashAttn: Boolean,
        vaeDecodeOnly: Boolean,
        sequentialLoad: Boolean?,
        allowOpenCl: Boolean,
        allowVulkan: Boolean,
        forceVulkan: Boolean,
        preferPerformanceMode: Boolean,
        token: String?,
        forceDownload: Boolean,
        flowShift: Float,
        loraModelDir: String?,
        loraApplyMode: LoraApplyMode,
        preferredBackend: io.aatricks.llmedge.runtime.ComputeBackend?,
        allowBackendFallbackToCpu: Boolean,
    ): StableDiffusion =
        withContext(Dispatchers.IO) {
            val resolved =
                StableDiffusionLoadSupport.resolveRequestedAssets(
                    context = context,
                    modelId = modelId,
                    filename = filename,
                    modelPath = modelPath,
                    vaePath = vaePath,
                    t5xxlPath = t5xxlPath,
                    taesdPath = taesdPath,
                    token = token,
                    forceDownload = forceDownload,
                    loraModelDir = loraModelDir,
                    validateResolvedAssets = StableDiffusionLoadSupport::validateResolvedAssets,
                    inferVideoModelMetadata = StableDiffusionLoadSupport::inferVideoModelMetadata,
                    onFallback = StableDiffusionLoadSupport::logLoadFallback,
                )

            StableDiffusionLoadSupport.createLoadedInstance(
                context = context,
                resolved = resolved,
                taesdPath = taesdPath,
                nThreads = nThreads,
                offloadToCpu = offloadToCpu,
                keepClipOnCpu = keepClipOnCpu,
                keepVaeOnCpu = keepVaeOnCpu,
                flashAttn = flashAttn,
                vaeDecodeOnly = vaeDecodeOnly,
                sequentialLoad = sequentialLoad,
                allowOpenCl = allowOpenCl,
                allowVulkan = allowVulkan,
                forceVulkan = forceVulkan,
                preferPerformanceMode = preferPerformanceMode,
                flowShift = flowShift,
                loraModelDir = loraModelDir,
                loraApplyMode = loraApplyMode,
                preferredBackend = preferredBackend,
                allowBackendFallbackToCpu = allowBackendFallbackToCpu,
            )
        }
}
